name: 'Setup gradle.properties file'
description: 'Copy Gradle properties file to the CI''s home directory.'
author: 'Simon Marquis'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  path:
    description: 'Gradle properties file path'
    default: '.github/gradle.properties'
    required: true

runs:
  using: composite
  steps:

    - if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      env:
        FILE: ${{ inputs.path }}
      run: |
        mkdir -p ~/.gradle
        cp "$FILE" ~/.gradle/gradle.properties

    - if: runner.os == 'Windows'
      shell: pwsh
      env:
        FILE: ${{ inputs.path }}
      run: |
        mkdir "$HOME\.gradle"
        cp "$env:FILE $HOME\.gradle\gradle.properties"
